name: tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.1'

      - name: install packages
        run: |
          pip install --upgrade pip
          pip install pytest

      - name: tests
        run: |
          pytest
